---
- connection: local
  hosts: localhost
  roles:
    - role: telusdigital.certbot
    - role: telusdigital.nginx
    - role: telusdigital.php
    - role: telusdigital.autodeploy
  vars:
    certbot_domain: "{% if environment_tier not in ['production'] %}{{ environment_tier }}{% endif %}.tls-me.telus.digital"
    nginx_ssl_enabled: yes
    nginx_ssl_enforced: yes
    nginx_php_enabled: yes
    nginx_creates_docroot: yes
    nginx_ssl_should_degrade_security_to_accomodate_old_browsers: yes
    nginx_ssl_pass_tls_version: yes
    autodeploy_repository_origin: https://github.com/telusdigital/tls-me.git
    autodeploy_repository_origin: master
    autodeploy_inital_deploy: yes
